import random
from datetime import datetime  
def generate_noshow_penalties(shards):
    """
    Create NoShowPenalty records for every booking with BookingStatus = 'NoShow'
    across all shards.
    """

    print("\nGenerating no-show penalty records (SHARDED)...")

    penalty_id_global = 1
    inserted_total = 0

    reasons = [
        "Passenger did not board — auto-detected at departure",
        "Passenger missed boarding window",
        "No-show detected at scheduled departure",
        "Passenger did not show up for boarding",
        "Late boarding attempt — trip already departed",
    ]

    # Iterate over ALL shards
    for shard_index, conn in enumerate(shards):
        cur = conn.cursor()

        # Get max penalty ID for this shard
        cur.execute("SELECT MAX(PenaltyID) FROM NoShowPenalty")
        max_penalty = cur.fetchone()[0] or 0

        penalty_id = max_penalty + 1

        # Fetch NoShow bookings for THIS shard only
        cur.execute("""
            SELECT b.BookingID, b.FareAmount, b.BookingTime
            FROM Booking b
            LEFT JOIN NoShowPenalty nsp ON b.BookingID = nsp.BookingID
            WHERE b.BookingStatus = 'NoShow'
            AND nsp.PenaltyID IS NULL
        """)

        noshow_bookings = cur.fetchall()

        print(f"  Shard {shard_index}: {len(noshow_bookings)} no-show bookings")

        inserted = 0

        for booking_id, fare, booking_time in noshow_bookings:

            penalty_amount = round(max(10.0, float(fare) * random.uniform(0.20, 0.30)), 2)
            reason = random.choice(reasons)
            auto_generated = random.choice([True, True, True, False])
            pay_status = random.choices(
                ["Paid", "Pending", "Waived"],
                weights=[60, 30, 10]
            )[0]

            cur.execute("""
                INSERT IGNORE INTO NoShowPenalty
                (PenaltyID, BookingID, DetectionTime, PenaltyAmount,
                 Reason, AutoGenerated, PaymentStatus, WaivedBy)
                VALUES (%s, %s, %s, %s, %s, %s, %s, NULL)
            """, (
                penalty_id,
                booking_id,
                booking_time,
                penalty_amount,
                reason,
                auto_generated,
                pay_status
            ))

            penalty_id += 1
            inserted += 1
            inserted_total += 1

            if inserted % 500 == 0:
                conn.commit()
                print(f"    {inserted} penalties inserted on shard {shard_index}...")

        conn.commit()
        print(f"  Shard {shard_index} done — {inserted} inserted.")

    print(f"\n✅ Total no-show penalties inserted — {inserted_total}")