"""
ADD THIS FUNCTION to generate_random_data.py
Place it after generate_cancellations() and before print_summary().
Then add the call inside __main__ as shown at the bottom.
"""

def generate_noshow_penalties():
    """
    Create NoShowPenalty records for every booking with BookingStatus = 'NoShow'
    that doesn't already have a penalty record.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON")
    cur  = conn.cursor()

    max_penalty = cur.execute(
        "SELECT MAX(PenaltyID) FROM NoShowPenalty"
    ).fetchone()[0] or 0

    # Only bookings that are NoShow and don't yet have a penalty record
    noshow_bookings = cur.execute("""
        SELECT b.BookingID, b.FareAmount, b.BookingTime
        FROM Booking b
        LEFT JOIN NoShowPenalty nsp ON b.BookingID = nsp.BookingID
        WHERE b.BookingStatus = 'NoShow'
        AND nsp.PenaltyID IS NULL
    """).fetchall()

    penalty_id = max_penalty + 1
    inserted   = 0

    reasons = [
        "Passenger did not board — auto-detected at departure",
        "Passenger missed boarding window",
        "No-show detected at scheduled departure",
        "Passenger did not show up for boarding",
        "Late boarding attempt — trip already departed",
    ]

    print(f"\nGenerating no-show penalty records for "
          f"{len(noshow_bookings)} no-show bookings...")

    for booking_id, fare, booking_time in noshow_bookings:
        # Penalty is 20–30% of the fare, minimum ₹10
        penalty_amount = round(max(10.0, float(fare) * random.uniform(0.20, 0.30)), 2)
        reason         = random.choice(reasons)
        auto_generated = random.choice([True, True, True, False])  # mostly auto
        # 60% paid, 30% pending, 10% waived
        pay_status = random.choices(
            ["Paid", "Pending", "Waived"],
            weights=[60, 30, 10]
        )[0]

        cur.execute("""
            INSERT OR IGNORE INTO NoShowPenalty
            (PenaltyID, BookingID, DetectionTime, PenaltyAmount,
             Reason, AutoGenerated, PaymentStatus, WaivedBy)
            VALUES (?, ?, ?, ?, ?, ?, ?, NULL)
        """, (penalty_id, booking_id, booking_time, penalty_amount,
              reason, auto_generated, pay_status))

        penalty_id += 1
        inserted   += 1

        if inserted % 500 == 0:
            conn.commit()
            print(f"  {inserted} penalties inserted...")

    conn.commit()
    conn.close()
    print(f"  No-show penalties done — {inserted} inserted.")


# ── In your __main__ block, add this call after generate_cancellations(): ──────
#
#   generate_cancellations()
#   generate_noshow_penalties()    # <-- add this line
#   generate_driver_assignments()
#
# ──────────────────────────────────────────────────────────────────────────────
